### ISSUE TITLE
InMemoryFileProvider has PhysicalPath hard coded to null

### ISSUE THREAD

**Issue by colin-young** [dazinator/Dazinator.AspNet.Extensions.FileProviders#19]
https://github.com/dazinator/Dazinator.AspNet.Extensions.FileProviders/blob/fde58f8649ea4deb6721814aa65d61f414ec8ed1/src/Dazinator.AspNet.Extensions.FileProviders/FileInfo/MemoryStreamFileInfo.cs#L28

Given one use case (wanting to avoid disk I/O) it makes perfect sense. Given another use case (unit testing) it can be a bit of a problem. I'll try to do a pull request with a fix. I'm guessing just an override on the constructor with a physical path parameter, but I'll see what I find when I give that a try.

**Comment by dazinator** [comment]
Im hesitant to accept setting that property to anything other than null or empty.. 

Could you elaborate on why it is important to have that be a physical path when unit testing?

**Comment by colin-young** [comment]
It's probably pointing to a weakness in the consumer of `IFileProvider`, as in 

```csharp
fileProvider
    .GetDirectoryContents(path)
    .Where(f => regex.IsMatch(f.Name))
    .Select(f => f.PhysicalPath);
```

might be the real problem, where I'm assuming there _is_ a physical path :)

I'm in the middle of converting a project from depending directly on `File.IO` to injecting `IFileProvider` and obviously running into some concepts and assumptions that will need to change.

**Comment by colin-young** [comment]
Confirmed: Yes, I needed to clean up the way I was handling File I/O internally to make it work properly with `IFileProvider`.

On the plus side, my unit testing did catch the fact that there was an issue, so hooray?

**Comment by dazinator** [comment]
Nice - glad its resolved! :-)
