### ISSUE TITLE
Fileprovider.Watch("") Does not work as expected

### ISSUE THREAD

**Issue by RPaetau** [dazinator/Dazinator.AspNet.Extensions.FileProviders#21]
Hello again, ive been using this in memory file magic some more, and ive found that the root directory (in this case i mean the root directory of any given provider) does not function properly, i cannot watch for changes in this root directory forexample, i get a null argument exception, which i dont get with the physical file provider forexample.. 

Its quite unsettling for me that my tests have completely different behaviors in this regard than my actual physical file provider.

``` C# 
        [Fact]
        public async Task GetFilesToBackupQuery_NewApproach_FilewatchIsApplied()
        {
            // Arrange
            var rootLocation = "/RAP";
            var directory = new InMemoryDirectory(rootLocation);
            var fp = new InMemoryFileProvider(directory);
            var watcher = fp.Watch(""); // This line throws, but i expect it to watch rootLocation
            var changeMe = false;
            watcher.RegisterChangeCallback((state) => { changeMe = true; }, new object());
            // Act
            directory.AddFile(rootLocation, new StringFileInfo("Test", "Test.txt"));
            await Task.Delay(2000);
            // Assert
            changeMe.Should().Be(true);
        }
```

**Comment by dazinator** [comment]
Interesting. Does `Watch("/")` work?

**Comment by RPaetau** [comment]
It doesent throw if i use it with "/", however this is different from how the physical file provider works (: 
It also dident register any change when i added that file a couple lines later (:

**Comment by RPaetau** [comment]
What do you think?

**Comment by dazinator** [comment]
Sounds like its a bug if its not behaving consistently with how Watch works with other providers like the PhysicalFileProvider.
I'd welcome a PR or added test coverage in this area. 
Otherwise it may be a while until I can look at it, but I'll add it to my list!

**Comment by dazinator** [comment]
You can see there are various tests for watch here: https://github.com/dazinator/Dazinator.AspNet.Extensions.FileProviders/blob/master/src/Dazinator.AspNet.Extensions.FileProviders.Tests/InMemoryFileProviderTests.cs#L215

These were produced at the time based on the physical file watcher tests.
However I can't see one that tests watching for a new file - only tests are for watching changes to an existing file.

It would be interesting to see how PhysicalFileWatcher handles that. 
Also I am pretty sure watching("") used to be correct, are you using asp.net core 1.X or 2.X ? Perhaps things have changed with physicalfileprovider in 2.X  compared to the 1.X version?

**Comment by RPaetau** [comment]
My manager has agreed to me spending some of my work time doing a PR, so ill see what i can figure out (: 
Im using 2.X of asp.net core (:

**Comment by RPaetau** [comment]
After digging around in your code a bit, it seems to me that this code was never designed to support watching directories, only files, and the tests seem to back this theory since there arent any that watches a directory (: So i think its gonna take a bit of a redesign.. This whole filters concept seems to work really nice for checking if a file has changed, but i cant really make it work with directories, since its not what its designed for sadly.. 
Im totally down for helping, but i think you might need to make some design considerations (: 

From what ive learned so far it seems that we can check if a path has a file extension (.txt ect) and if it does not then we can add a "/*" wildcard to make the globbing thing work, but then we get another design issue later when it then tries to notify the watcher cause it cannot find a watcher with the path "/*" cause the watcher would be watching "". 

Im gonna keep going for a while here, i just wanted to put down these thoughts while they were still fresh!

**Comment by dazinator** [comment]
I am up for changes in design that facilitate the end goal of mirroring physicalfileprovider behaviours in terms of watching.

It would be good initially just to get a few failing tests up that we want to pass, and that PhysicalFileProvider passes with - if you get a chance to add a few such tests we can then discuss any design changes in terms of making those tests pass.

**Comment by RPaetau** [comment]
Closing here, thanks for this, it was my first contribution to an OS framework, and it was a fun and educating experience (:

**Comment by RPaetau** [comment]
@dazinator Just one last comment, any plans on making a new release, or should i just use the unstable version for a while? (:

**Comment by dazinator** [comment]
If you can use the latest unstable nuget package for now that would be great. I will issue a new release but I want to ensure there has been some time for this change to sink in - if you hit any further issues please let me know.
