### ISSUE TITLE
Updating to latest .NET Core 2.0 libs.

### ISSUE THREAD

**Issue by pauldotknopf** [dazinator/Dazinator.AspNet.Extensions.FileProviders#31]
I tried to add a reference to the NuGet package, and I got build errors because the references were outdated (using .NET Core 2.0/2.1).

Doing this would force you to be .NET Standard 2.0 as well, something to think about.

**Comment by dazinator** [comment]
I have been using this in a net core and netcore 2.1.0 app without any problems.
When you add this package, it will pull in baseline versions of dependencies if you don't already have them installed:

```
Microsoft.AspNetCore.Hosting.Abstractions (>= 1.0.2)
Microsoft.AspNetCore.Http.Abstractions (>= 1.0.2)
Microsoft.Extensions.FileProviders.Abstractions (>= 1.0.1)
NETStandard.Library (>= 1.6.1)
```

However they are only the baselines. You can update those dependencies to 2.0 or 2.1.0 and it should all still work. In a 2.0.0 or 2.1.0 mvc application, it would probably already satisfy those dependencies.

I'll close this for now. Can reopen if there is still any specific problem to look at.
